MyBlog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'posts#index'
resources :posts,only: [:show,:index] do
  resources :comments
end
resources:tags, only:[:show]
resources :categories,only: [:show]

namespace :admin do
  resources :posts,except: [:show, :index]
  resources :categories,except: :show
end
end

MyBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyBlog/app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many:posts,dependent: :destroy
  validates :name, presence:true
end

MyBlog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence:true
end

MyBlog/app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_rich_text :body
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings
  validates :title, :summary, :body, :all_tags, presence:true
  belongs_to :category

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags=names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
  
end

MyBlog/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name,count(taggings.tag_id) as count").
    joins(:taggings).group("name,taggings.tag_id")
  end
  
end

MyBlog/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

MyBlog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable
end

MyBlog/app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  layout "admin"

  protected
  def check_admin
    redirect_to root_path, alert:"У вас немає прав доступу до даної сторінки" unless current_user.admin?
  end
  
end

MyBlog/app/controllers/admin/categories_controller.rb
  class Admin::CategoriesController < Admin::AdminController
    before_action:set_category,only:[:edit,:update,:destroy]

    def index
      @categories=Category.all
    end

    def new
      @category=Category.new
      @categories=Category.all.order(:name)
    end

    def create
      @category=Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, success: 'Категорія була успішно створена'
      else
        @categories=Category.all.order(:name)
        flash.now[:danger] = 'Категорія не була створена'
        render :new
      end
    end

    def edit
      @categories = Category.where("id != #{@category.id}").order(:name)
    end

    def update
      if @category.update_attributes(category_params)
        redirect_to admin_categories_path, success: 'Категорія була успішно оновлена'
      else
        @categories = Category.where("id != #{@category.id}").order(:name)
        flash.now[:danger] = 'Категорія не була оновлена'
        render :edit
      end
    end

    def destroy
      @category.destroy
      redirect_to admin_categories_path,success: 'Категорія була успішно видалена'
    end

    private
    def set_category
      @category=Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name,:parent_id)
    end
    
  end

MyBlog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action:set_post,only:[:edit,:update,:destroy]

  def index
    posts=Post.paginate(page: params[:page],per_page: 5)
    posts.reverse_each do |curpost|
      @posts << curpost
    end
  end

  def show
  end

  def new
    @post=Post.new
  end

  def create
    @post=Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Стаття була успішно створена'
    else
      flash.now[:danger] = 'Стаття не була створена'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Стаття була успішно оновлена'
    else
      flash.now[:danger] = 'Стаття не була оновлена'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path,success: 'Стаття була успішно видалена'
  end

  private
  def set_post
    @post=Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:summary,:body, :image, :all_tags,:category_id)
  end
  
end

MyBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning
end

MyBlog/app/controllers/categories_controller.rb
  class CategoriesController < ApplicationController
    before_action:set_category,only: :show

    def show
       @posts=Post.where(category_id: [@category.subtree_ids]).paginate(page:params[:page],per_page: 5)
    end
    
    private
    def set_category
      @category=Category.find(params[:id])
    end

  end

MyBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post=Post.find(params[:post_id])
    @comment=@post.comments.new(comments_params)
    if user_signed_in?
    str=current_user.email
    str1=str[0..str.index('@')-1]
    @comment.username=str1
    @comment.save
  end
    redirect_to post_path(@post)
  end

  def destroy
    @post=Post.find(params[:post_id])
    @comment=@post.comments.find(params[:id])
    @comment.destroy
    redirect_to @post,success: 'Коментарій був успішно видалений'
  end

  private
  def comments_params
    params.require(:comment).permit(:username,:body,:id,:post_id)
  end
  
end

MyBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action:set_post,only:[:show]

  def index
    @posts=Post.paginate(page: params[:page],per_page: 5)
  end

  def show
  @comment = Comment.new
  end

  private
  def set_post
    @post=Post.find(params[:id])
  end
  
end

MyBlog/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag=Tag.find_by(name:params[:id])
    @posts=@tag.posts
  end

end

MyBlog/app/helpers/admin_helper.rb
module AdminHelper
end

MyBlog/app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumbs(category)
    result=[]
    category.ancestors.each do |ancestor|
      result<< content_tag(:li, class: "breadcrumb-item") do
        link_to(ancestor.name,ancestor)
      end
    end
      result << content_tag(:li, category.name,class:"breadcrumb-item active")
      result.join('').html_safe
  end
  def bootstrap_class_for(name)
    {
      success: "alert-success",
      error: "alert-danger",
      danger: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end
end

MyBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

MyBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

MyBlog/app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do|tag|
      index=tag.count.to_f/max.count*(classes.size-1)
      yield(tag,classes[index.round])
    end
  end
end

MyBlog/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])%>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

MyBlog/app/views/admin/categories/_form.html.erb
<% if @category.errors.any?%>
<div class="alert alert-danger">
  <h5><%= t('common.errors')%></h5>
    <ul>
     <%@category.errors.full_messages.each do |msg|%>
      <li><%=msg%></li>
     <%end%>
    </ul>
</div>
<%end%>
<%=form_for [:admin,@category] do |f| %>
<div class="form-group">
  <%=f.label :name%>
  <%=f.text_field:name,class:'form-control'%>
</div>
<div class="form-group">
  <%=f.label :parent_id%>
  <%=f.collection_select :parent_id,@categories,:id,:name,{include_blank:true},class:'form-control'%>
</div>
<div class="form-group">
  <%=f.submit t('.submit',action: @category.new_record? ? 'Створити' : 'Змінити'),class:'btn btn-primary'%>
  <%=link_to t('common.back'),:back,class:'btn btn-outline-secondary'%>
</div>
<%end%>

MyBlog/app/views/admin/categories/edit.html.erb
<h1><%=t('.title')%></h1>
<%=render 'form'%>

MyBlog/app/views/admin/categories/index.html.erb
<h1><%=t('.title')%></h1>
<div class="buttons_panel">
  <%=link_to 'Нова категорія', new_admin_category_path,class: 'btn btn-outline-primary btn-sm'%>
</div>
<section id="categories">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Назва</th>
        <th>Категорія батько</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each.with_index do |category,index|%>
      <tr>
        <td><%=index+1%></td>
        <td><%=category.name%></td>
        <td><%=category.parent.name if category.parent.present?%></td>
        <td>
          <%=link_to 'Редагувати',edit_admin_category_path(category),class:'btn btn-outline-primary btn-sm'%>
          <%=link_to 'Видалити',admin_category_path(category),method: :delete,data:
          {confirm:'Ви хочете видалити цю категорію?'},class:'btn btn-outline-danger btn-sm'%>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</section>

MyBlog/app/views/admin/categories/new.html.erb
<h1><%=t('.title')%></h1>
<%=render 'form'%>

MyBlog/app/views/admin/posts/_form.html.erb
<% if @post.errors.any?%>
<div class="alert alert-danger">
  <h5><%= t('common.errors')%></h5>
   <ul>
   <%@post.errors.full_messages.each do |msg|%>
    <li><%=msg%></li>
   <%end%>
   </ul>
</div>
<%end%>
<%=form_for [:admin,@post],html:{ multipart: true} do |f| %>
<div class="form-group">
  <%=f.label :title%>
  <%=f.text_field:title,class:'form-control'%>
</div>
<div class="form-group">
  <%=f.label :summary%>
  <%=f.text_area :summary,class:'form-control'%>
</div>
<div class="form-group">
  <%=f.label :body%>
  <%=f.rich_text_area :body,class:'editor'%>
</div>
<div class="form-group">
  <%=f.label :category_id%>
  <%=f.collection_select :category_id,Category.order(:name),:id,:name,{include_blank:true},class:'form-control'%>
</div>
<div class="form-group">
  <%=f.label :all_tags%>
  <%=f.text_field :all_tags,class:'form-control'%>
</div>
<div class="form-group">
  <%=f.file_field :image%>
</div>
<div class="form-group">
  <%=f.submit t('.submit',action: @post.new_record? ? 'Створити' : 'Змінити'),class:'btn btn-primary'%>
  <%=link_to t('common.back'),:back,class:'btn btn-outline-secondary'%>
</div>
<%end%>

MyBlog/app/views/admin/posts/edit.html.erb
<h1><%=t('.title')%></h1>
<%= render 'form'%>

MyBlog/app/views/admin/posts/new.html.erb
<h1><%=t('.title')%></h1>
<%= render 'form'%>

MyBlog/app/views/categories/show.html.erb
<%=render 'shared/breadcrumb',category:@category%>
<h1><%=@category.name%></h1>
<section id="posts">
  <%=render @posts%>
</section>
<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer'%>

MyBlog/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Адмін Панель</a>
  <ul class="nav navbar">
    <li class="nav-item <%= 'act' if current_page?(root_path) || current_page?(posts_path)%>">
      <a class="nav-link" href="<%= root_path %>">Всі статті</a>
    </li>
      </ul>
  <ul class="nav navbar right">
    <%if user_signed_in? %>
    <li class="nav-item">
      <%=link_to "Вихід",destroy_user_session_path,method: :delete,class: "nav-link"%>
    </li>
    <%else %>
    <li class="nav-item">
      <%=link_to "Вхід",new_user_session_path,class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%=link_to "Реєстрація",new_user_registration_path,class: "nav-link"%>
    </li>
    <%end%>
  </ul>
</nav>
</div>
<div class="container">
<nav class="navbar navbar-light" style="background-color: #292b2e">
<ul class="nav navbar">
    <% Category.order(:name).roots.each do |category|%>
    <li class="nav-item <%='act' if current_page?(category_path(category))%>">
      <%=link_to category.name,category,class:'nav-link'%>
    </li>
    <%end%>
</ul>
</nav>
</div>
  <div class="container main">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |name,message|%>
        <div class="alert <%=bootstrap_class_for(name)%>">
          <button class="close"data-dismiss="alert">&times;</button>
          <%=message%>
          </div>
        <%end%>
        </div>
        </div>
    <div class="row">
    <div class="col-md-9">
       <%= yield %>
    </div>
    <div class="col-md-3">
      <%= render 'shared/submenu'%>
      <div class="tag_cloud">
        <h2>Теги</h2>
      <div class="editview_2">
       <%tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class|%>
       <%=link_to tag.name,tag_path(tag.name), class: css_class%>
       <%end%>
       </div>
       </div>
    </div>
  </div>
  </div>
</body>
</html>

MyBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-light" style="background-color: #e3f2fd">
    <a class="navbar-brand" href="#">Мій блог</a>
  <ul class="nav navbar">
    <li class="nav-item <%= 'act' if current_page?(root_path) || current_page?(posts_path)%>">
      <a class="nav-link" href="<%= root_path %>">Всі статті</a>
    </li>
    </ul>
  <ul class="nav navbar">
    <%if user_signed_in? %>
    <li class="nav-item">
      <%=link_to "Вихід",destroy_user_session_path,method: :delete,class: "nav-link"%>
    </li>
    <%else %>
    <li class="nav-item">
      <%=link_to "Вхід",new_user_session_path,class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%=link_to "Реєстрація",new_user_registration_path,class: "nav-link"%>
    </li>
    <%end%>
  </ul>
</nav>
</div>
<div class="container">
<nav class="navbar navbar-light" style="background-color: #a4c4f5">
<ul class="nav navbar">
  <% if user_signed_in? && current_user.admin?%>
  <li class="nav-item <%= 'act' if current_page?(admin_categories_path)%>">
    <a class="nav-link" href="<%= admin_categories_path %>">Всі категорії</a>
  <%end%>
<% Category.order(:name).roots.each do |category|%>
<li class="nav-item <%='act' if current_page?(category_path(category))%>">
  <%=link_to category.name,category,class:'nav-link'%>
</li>
<%end%>
</ul>
</nav>
</div>
  <div class="container main">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |name,message|%>
        <div class="alert <%=bootstrap_class_for(name)%>">
          <button class="close"data-dismiss="alert">&times;</button>
          <%=message%>
          </div>
        <%end%>
        </div>
        </div>
    <div class="row">
    <div class="col-md-9">
       <%= yield %>
    </div>
    <div class="col-md-3">
      <%= render 'shared/submenu'%>
      <div class="tag_cloud">
      <h2>Теги</h2>
      <div class="editview_2">
       <%tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class|%>
       <%=link_to tag.name,tag_path(tag.name), class: css_class%>
       <%end%>
       </div>
       </div>
    </div>
  </div>
  </div>
</body>
</html>

MyBlog/app/views/posts/_comments.html.erb
<% if @post.errors.any?%>
<div class="alert alert-danger">
  <h5><%= t('common.errors')%></h5>
  <ul>
   <%@post.comments.errors.full_messages.each do |msg|%>
   <li><%=msg%></li>
   <%end%>
  </ul>
</div>
<%end%>
<h2>Коментарі</h2>
<div style="background-color:#e0fff4">
 <%@post.comments.each do |comment|%>
   <strong><%=comment.username%></strong>: <%=comment.body%><br>
   <small>
     <time>
      <%=comment.created_at.to_date.strftime("%d %B, %Y")%>
     </time>
     <% if current_user!=nil%>
     <% if current_user.admin? || current_user.email[0..current_user.email.index('@')-1]==comment.username%>
     <%=link_to 'Видалити',post_comment_path(comment.post,comment),method: :delete,data:
      {confirm:'Ви хочете видалити цей коментарій?'}%>
     <%end%>
     <%end%>
   </small>
  <br><br>
 <%end%>
</div>
<% if user_signed_in?%>
<h2>Додавання коментарів</h2>
<%=form_for [@post, @post.comments.build] do |f| %>
<div class="form-group">
  <%=f.text_area :body ,class:'form-control'%>
</div>
<div class="form-group">
  <%=f.submit 'Створити',class:'btn btn-primary'%>
</div>
<%end%>
<%end%>

MyBlog/app/views/posts/_post.html.erb
<article class="post" style="background-color:#e0fff4">
  <section class="post-head">
    <h2><%=link_to post.title,post_path(post)%></h2>
    <small>
      <time>
       <%=post.created_at.to_date.strftime("%d %B, %Y")%>
      </time>
      <% if post.category.present?%>
        |
        <%=link_to post.category.name,post.category%>
      <%end%>
      <% if user_signed_in? && current_user.admin?%>
        |
        <%=link_to t('common.edit'),edit_admin_post_path(post)%>
        |
        <%=link_to t('common.delete'),admin_post_path(post),method: :delete,data:
        {confirm:'Ви хочете видалити цю статтю?'}%>
      <%end%>
    </small>
  </section>
  <section class="post-summary clearfix">
    <%=image_tag post.image.url(:thumb),class:'thumb' if post.image? %>
    <%=post.summary%>
  </section>
  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{|t| link_to t, tag_path(t),class:'badge badge-primary'}.join(' ')%>
  </section>
</article>

MyBlog/app/views/posts/index.html.erb
<h1><%=t('.title')%></h1>
<% if user_signed_in? && current_user.admin?%>
<%=link_to 'Нова стаття',new_admin_post_path,class:'btn btn-outline-primary btn-sm'%>
<%end%>
<section id='posts'>
 <%=render @posts %>
</section>
<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer'%>

MyBlog/app/views/posts/show.html.erb
<%=render 'shared/breadcrumb',category:@post.category%>
<article class="post" style="background-color:#e0fff4">
  <section class="post-head">
    <h1><%=@post.title%></h1>
    <small>
      <time>
       <%=@post.created_at.to_date.strftime("%d %B, %Y")%>
      </time>
      <% if @post.category.present?%>
        |
        <%=link_to @post.category.name,@post.category%>
      <%end%>
      <% if user_signed_in? && current_user.admin?%>
        |
        <%=link_to t('common.edit'),edit_admin_post_path(@post)%>
        |
        <%=link_to t('common.delete'),admin_post_path(@post),method: :delete,data:
        {confirm: t('common.question')}%>
      <%end%>
    </small>
  </section>
  <section class="post-body">
    <%=@post.body%>
  </section>
</article>
<%=render 'comments'%>

MyBlog/app/views/shared/_breadcrumb.html.erb
<%if category.present? && category.parent%>
<ol class="breadcrumb">
  <%=build_breadcrumbs(category)%>
</ol>
<%end%>

MyBlog/app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2>Категорії</h2>
  <ul class="nav nav-pills nav-stacked editview">
    <%Category.roots.each do |category|%>
    <li class="nav-parent nav-item">
    <%=link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
    <%=render 'shared/submenu_categories',categories: category.root.descendants.arrange%>
    </li>
    <%end%>
  </ul>
</div>

MyBlog/app/views/shared/_submenu_categories.html.erb
<ul class="nav nav-pills nav-stacked nested_nav">
  <%categories.each do|category,children|%>
  <li class="nav-child">
  <%=link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
  <%=render 'shared/submenu_categories',categories: children if children.present?%>
  </li>
  <%end%>
</ul>

MyBlog/app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<% if @tag.posts.empty? %>
<h2>Статтей немає</h2>
<%else %>
<%= render @tag.posts%>
<%end%>